apiVersion: v1
kind: List
items:
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    name: finance
    namespace: tenant-1
  spec:
    template:
      metadata:
        labels:
          app: finance
      spec:
        containers:
        - image: finance-service:latest
          imagePullPolicy: IfNotPresent
          name: finance
          ports:
          - containerPort: 8080
            protocol: TCP
          resources: {}
-
  kind: Service
  apiVersion: v1
  metadata:
    labels:
      app: finance
    name: finance
    namespace: tenant-1
  spec:
    type: LoadBalancer
    ports:
    - port: 8080
      targetPort: 8080
    selector:
      app: finance
-
  apiVersion: extensions/v1beta1
  kind: Ingress
  metadata:
    name: finance
    namespace: tenant-1
  spec:
    rules:
    - host: tenant-1
      http:
        paths:
        - path: /finance
          backend:
            serviceName: finance
            servicePort: 8080
  